map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]
#robot_radius: 0.7
inflation_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: odom, data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}
